### ISSUE TITLE
How to change dpi

### ISSUE THREAD

**Issue by myscreen** [lvillani/android-cropimage#55]
Default dpi for image is 92 , how can I modify it ?

**Comment by lvillani** [comment]
You mean when viewing the image from within `CropImage` activity?

**Comment by myscreen** [comment]
I customize your code and now it saves the file in external storage. when I get properties from the file in pc dpi is 96 which I need to reduce it.

**Comment by lvillani** [comment]
I don't understand. Where are you getting the DPI value from? EXIF tags? The only meaningful dimension of an image is its size in pixels. You probably want to scale the image, in which case you can do that by using the `aspectX/aspectY` and `outputX/outputX` parameter within `CropImageIntentBuilder` constructor.

**Comment by myscreen** [comment]
as I said I stored the cropped file in external storage, this is image file properties

![weq](https://cloud.githubusercontent.com/assets/14212198/11363961/ff2a33b0-92d7-11e5-96cc-5e367ea5164d.PNG)

**Comment by lvillani** [comment]
The resolution shown there is arbitrary and should match the screen's resolution, unless it is written as an EXIF tag, that this library doesn't handle anyway.

You can add custom EXIF tag using another library after you have cropped the image.

I'm closing this issue since adding support for custom EXIF tags goes beyond the scope of this library.
